// Login with basic authentication using correct credentials admin:123
###
# @name loginAdminCorrect
POST http://localhost:8080/authenticate/
Authorization: Basic YWRtaW46MTIz

// Login with basic authentication using wrong credentials
###
POST http://localhost:8080/authenticate
Authorization: Basic admin:1234

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

// get all users without token
###
http://localhost:8080/user

// get all users with admin token
###
http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NDU3NDYzNjEsImV4cCI6MTY0NzM5MjQwNzQwNn0._U3TEfvtUvL9T3HrhSavq0HBE0ERvOswsG-G6iWHgUM

// Login for manfred
###
POST http://localhost:8080/authenticate/
Authorization: Basic bWFuZnJlZDphc2Rm

// verify manfred
###
http://localhost:8080/signup/confirm/ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxiV0ZwYkNJNkluUnlZWE5vYldWb1lYSmtRR1Y0YVhOMGFXVnlkQzV1WlhRaUxDSnBZWFFpT2pFMk5EWTBOVFEyTVRnc0ltVjRjQ0k2TVRZME9ERXdORFkzTXpVd04zMC5IdzZUbFhvdjhLcnd0WGdfNDVvRFNDWUVXc3RlRW1WU2VReXUtMzl0NGpR


###
// creating manfred by himself (needs to be verified after that)
POST http://localhost:8080/signup
Content-Type: application/json

{
  "userID": "manfred",
  "userName": "Manfred Mustermann",
  "email": "trashmehard@existiert.net",
  "password": "asdf"
}