###
// delete all previous
DELETE http://localhost:8080/publicUsers/deleteAllUsers

###
// no users should be in the database here
http://localhost:8080/publicUsers/

###
// creating first user who is admin | throws 409 (conflict) because admin is created by default
POST http://localhost:8080/publicUsers/
Content-Type: application/json

{
  "userID": "admin",
  "userName": "Udo Müller",
  "password": "123",
  "isAdministrator": true
}

###
// find admin in database
GET http://localhost:8080/publicUsers/admin

###
// creating second user who is not admin
POST http://localhost:8080/publicUsers/
Content-Type: application/json

{
  "userID": "manfred",
  "userName": "Manfred Mustermann",
  "email": "trashmehard@existiert.net",
  "password": "asdf"
}

###
// find manfred in database
POST http://localhost:8080/publicUsers/getUserByID
Content-Type: application/json

{
  "userID": "manfred"
}

###
// update manfred
PUT http://localhost:8080/publicUsers/manfred
Content-Type: application/json

{
  "userID": "manfred",
  "userName": "Manfred Müller"
}

###
// 2 users should be in the database now
http://localhost:8080/publicUsers/

###
// try creating user without userID - expect 400 (bad request)
POST http://localhost:8080/publicUsers/
Content-Type: application/json

{
  "userName": "Manfred Mustermann",
  "email": "trashmehard@existiert.net",
  "password": "asdf"
}

###
// try updating user who doesn't exist - expect 404 (not found)
PUT http://localhost:8080/publicUsers/manni
Content-Type: application/json

{
  "userID": "manfred",
  "userName": "Manfred Mustermann",
  "email": "trashmehard@existiert.net",
  "password": "asdf"
}

###
POST http://localhost:8080/publicUsers/deleteUserByID
Content-Type: application/json

{
  "userID": "admin"
}

###
DELETE http://localhost:8080/publicUsers/manfred
Content-Type: application/json

{
  "userID": "manfred"
}